Feature/domain models
polarxdev/FinancialPortfolio pull request #1
Opened 2024-07-07 17:40 UTC by tosqaaa

# Changes
Domain models
Simple recycler view for all assets list
Navigation
# Screenshots

![assets_list](https://github.com/polarxdev/FinancialPortfolio/assets/123359559/d97335d5-fbf9-4902-84b6-13a3c06de80e)

2024-07-07 17:49 UTC, polarxdev approved these changes

2024-07-07 18:50 UTC, pzinkevich42innowise commented
<img width="178" alt="image" src="https://github.com/polarxdev/FinancialPortfolio/assets/172857914/5d617165-d150-4142-937b-b5eb55a0957b">

норм так, да?

2024-07-07 18:55 UTC, tosqaaa commented
> <img width="178" alt="image" src="https://github.com/polarxdev/FinancialPortfolio/assets/172857914/5d617165-d150-4142-937b-b5eb55a0957b">
> 
> норм так, да?

Сори, я затупил. Совсем забыл что так много файлов сразу закинул. Хотел основную архитектуру приложения выстроить и сильно увлёкся. Ещё раз извиняюсь

2024-07-07 19:29 UTC, pzinkevich42innowise requested changes

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/assetsList/AssetsListFragment.kt
> +    private lateinit var recyclerView: RecyclerView
А вот тут есть вопросы, зачем это делать? А если и делать, то точно не так - 100% утечка памяти

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/assetsList/AssetsListViewModel.kt
> +    private val repository = AssetsListRepository()
ну пока ок, но это точно надо будет потом поправить на DI-решение

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/home/HomeFragment.kt
> +        val binding = FragmentHomeBinding.bind(view)
тоже вынести на уровень класса

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/home/HomeFragment.kt
> +    private var fragmentHomeBinding: FragmentHomeBinding? = null
```suggestion
    private var _fragmentHomeBinding: FragmentHomeBinding? = null
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/portfolio/PortfolioFragment.kt
> +        val binding = FragmentPortfolioBinding.bind(view)
аналогично

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/rv/AssetListAdapter.kt
> +        fun getAssetType(asset: Asset): AssetType {
```suggestion
        fun Asset.toLayoutType(): AssetType {
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/rv/AssetListAdapter.kt
> +        return AssetType.getAssetType(items[position]).layoutResId
можно было и в краткой форме

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/rv/AssetListAdapter.kt
> +        return items.size
тоже в краткой форме можно

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/rv/AssetViewHolder.kt
> +                else -> throw IllegalArgumentException("Invalid view type")
Принцип Открытости-Закрытости нарушен: при расширении системы, сюда необходимо будет вносить изменения
Принцип подстановки Лисков нарушен - при появлении новых наследников этот метод (без изменений) работать не будет, будет throw
Принцип инверсии зависимостей нарушен - абстрактный класс зависит от реализации

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/settings/SettingsFragment.kt
> +        val binding = FragmentSettingsBinding.bind(view)
аналогично

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +    <LinearLayout
А без Linear никак?

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_portfolio.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_portfolio.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_portfolio.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_settings.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_settings.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_settings.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-07 19:29 UTC, pzinkevich42innowise commented on gradle/libs.versions.toml
> +androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
При смене версии надо будет менять имя библиотеки? Вместо одной строчки менять как минимум 3 (версия + тут + build gradle)

2024-07-08 14:15 UTC, pzinkevich42innowise requested changes

2024-07-08 14:15 UTC, pzinkevich42innowise commented on gradle/libs.versions.toml
> +androidx-navigation-ui-ktx-v253 = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
Мои комментарии для вас что, шутка какая-то?)

2024-07-09 17:13 UTC, tosqaaa commented
Много файло в последнем коммите из-за добавления linter, и из-за исправлений которые требовал linter

2024-07-09 18:37 UTC, pzinkevich42innowise requested changes

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/data/AssetListRepositoryImpl.kt
> +    }
```suggestion
    private var assets = getAssets()
```

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/di/DataModule.kt
> +    }
Почему provides, а не binds?

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/di/DomainModule.kt
> +@InstallIn(ViewModelComponent::class)
Почему ViewModelComponent?

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/domain/usecase/GetAssetListUseCase.kt
> +class GetAssetListUseCase(private val assetListRepository: AssetListRepository) {
На каждый чих планируете создавать по маленькому классику с логикой? Я не запрещаю, на вкус и цвет, как говорится, но кмк это излишне

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/domain/usecase/GetAssetListUseCase.kt
> +    fun execute(): List<Asset> {
Если метод вдруг называется execute, то может есть смысл перегрузить оператор invoke?

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/assetList/AssetListFragment.kt
> +        recyclerView.layoutManager = LinearLayoutManager(requireContext())
Через XML никак нельзя это сделать?

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/rv/AssetListAdapter.kt
> +                else -> throw IllegalArgumentException("Invalid AssetType")
Кстати, если таких проверок планируется много, то можно подумать в сторону того, чтобы Asset сделать sealed

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/rv/AssetListAdapter.kt
> +        }
В этом случае можно попробовать перенести каст внутрь ViewHolder, чтобы не расширять тут адаптер

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/rv/AssetViewHolder.kt
Го переосмыслим содержимое этого файла. Можно сделать один файл с абстракциями, а далее каждый холдер вместе со своей фабрикой раскидать по разным файлам. Получится один файл на каждый тип холдера + фабрика, которая его создаёт. Ничего лишнего

2024-07-09 18:37 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_portfolio.xml
> +        app:layout_constraintStart_toStartOf="parent" />
А тулбар чем не подошёл?

2024-07-16 19:23 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
типа пофиг на коменты?

2024-07-16 19:24 UTC, pzinkevich42innowise approved these changes

2024-07-17 08:48 UTC, merged