Database
polarxdev/FinancialPortfolio pull request #10
Opened 2024-08-20 18:38 UTC by polarxdev

### **Added database functionality using ROOM**

2024-08-20 18:38 UTC, polarxdev commented
Старый dataSource пока что оставил, чтобы отображались ассеты

2024-08-21 15:18 UTC, Valentin2508247 requested changes

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/data/PortfolioAssetListRepositoryImpl.kt
можешь удалить репозиторий
подменить data source для тестовый целей сможешь через DI

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/data/database/converters/Converters.kt
> +        return date.format(dateFormatter)
может выбрасывать краши

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/data/database/converters/Converters.kt
> +        return LocalDate.parse(dateString, dateFormatter)
может выбрасывать краши

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/data/database/local/LocalPortfolioTableDataSource.kt
> +        return withContext(Dispatchers.IO) {
переопределяй Dispatchers в репозитории (уже сделано)

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/domain/interactor/PortfolioAssetListInteractor.kt
> +import com.example.financialportfolio.data.database.entity.PortfolioTable
притянул в domain слой data зависимость

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/domain/repository/PortfolioAssetsListRepository.kt
> +import com.example.financialportfolio.data.database.entity.PortfolioTable
притянул в domain слой data зависимость

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/domain/entity/Assets.kt
> +    @Embedded
зачем тебе и TypeConverter, и Embedded?

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/domain/entity/Assets.kt
> +import androidx.room.Embedded
в domain затянул data зависимости

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/portfolio/PortfolioViewModel.kt
> +                _portfolioAssetList.postValue(portfolioAssets)
_portfolioAssetList.value = portfolioAssets

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/data/database/entity/PortfolioTable.kt
> +    val asset: Asset,
зачем и embedded, и TypeConvertor?

2024-08-21 15:18 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/data/database/converters/Converters.kt
> +    fun fromAsset(asset: Asset): String {
Зачем одновременно и embedded, и TypeConvertor?

2024-08-26 07:36 UTC, Valentin2508247 requested changes

2024-08-26 07:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/data/database/converters/Converters.kt
> +        "Try later"
unreachable code

2024-08-26 07:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/data/database/converters/Converters.kt
> +
строка

2024-08-26 07:36 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/domain/entity/PortfolioAsset.kt
> +    var id: Int,
зачем поменял на var?

2024-09-13 18:49 UTC, merged