Feature/asset detail
polarxdev/FinancialPortfolio pull request #2
Opened 2024-07-17 13:19 UTC by polarxdev

### Changes
Added fragment of asset details

2024-07-17 14:25 UTC, tosqaaa commented on app/src/main/java/com/example/financialportfolio/presentation/assetList/AssetListFragment.kt
>                      ).show()
Эти Toast можно убрать, я их как заглушки оставлял. Просто оставь переход на другой фрагмент

2024-07-17 14:27 UTC, tosqaaa commented on app/src/main/res/layout/fragment_asset_detail.xml
> +        android:id="@+id/textView2"
Может тут добавим осмысленные id. Типа metadata_label. В дальнейшем будет проще ориентироваться при верстке

2024-07-17 14:42 UTC, tosqaaa commented on app/src/main/java/com/example/financialportfolio/presentation/assetDetail/AssetDetailFragment.kt
> +            }
Возможно потом нам надо будет это переделать, т.к. при добавлении новых активов придется лезть в функцию и ее изменять, как будто не очень хорошо. Пока что норм

2024-07-17 14:44 UTC, tosqaaa commented on app/src/main/java/com/example/financialportfolio/presentation/assetDetail/AssetDetailFragment.kt
> +        }
А что если не будет asset с таким id. Наверно надо как то обработать этот случай

2024-07-17 14:45 UTC, tosqaaa reviewed
Надо подправить некоторые моменты, я полагаю.

2024-07-19 19:02 UTC, tosqaaa approved these changes
✔

2024-07-22 14:33 UTC, Valentin2508247 requested changes

2024-07-22 14:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/assetDetail/AssetDetailFragment.kt
> +
пустая строка?

2024-07-22 14:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/assetDetail/AssetDetailFragment.kt
> +    fun bindInfo(model: Asset){
плохое форматирование, пропущены робелы

2024-07-22 14:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/assetDetail/AssetDetailFragment.kt
> +            Toast.makeText(context, "ssss", Toast.LENGTH_SHORT).show()
ssss?

2024-07-22 14:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/assetDetail/AssetDetailFragment.kt
> +        val id = args.Id
тут должен быть вызов метода viewModel.loadAssetById(id)
обработка результата через observe livedata

2024-07-22 14:33 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_asset_detail.xml
> +            android:text=""
не нужна строка

2024-07-22 14:33 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_asset_detail.xml
> +        android:layout_width="wrap_content"
android:layout_width="0dp"
тут constraints стоят

2024-07-22 14:33 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_asset_detail.xml
> +        android:text=""
не нужно

2024-07-22 14:33 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_asset_detail.xml
> +        android:text=""
аналогично

2024-07-22 14:33 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_asset_detail.xml
> +        android:text=""
аналогично

2024-07-22 14:33 UTC, Valentin2508247 commented on app/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.1"
зачем зависимость?

2024-07-24 09:16 UTC, Valentin2508247 requested changes

2024-07-24 09:16 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/assetDetail/AssetDetailFragment.kt
> +        try {
давай сделаем обработку ошибок во viewModel

во фрагменте оставим только viewModel.loadAssetById(id.dec()) и observe livedata с ошибками

2024-07-24 13:24 UTC, polarxdev commented
### P.S.
В последнем коммите использовал interactor т.к. возникли ошибки из-за фикса конфликтов в позапрошлом коммите.

2024-07-25 09:34 UTC, Valentin2508247 approved these changes

2024-07-25 09:42 UTC, merged