Refactoring
polarxdev/FinancialPortfolio pull request #8
Opened 2024-07-27 11:14 UTC by tosqaaa

## Changes
- Reorganized files
- Renamed files
- Little corrections

2024-07-27 14:38 UTC, polarxdev approved these changes

2024-07-29 09:09 UTC, Valentin2508247 requested changes

2024-07-29 09:09 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/portfolio/rv/PortfolioAssetViewHolder.kt
> +            model.let {
зачем model.let?

2024-07-29 11:26 UTC, Valentin2508247 approved these changes

2024-07-29 11:31 UTC, merged