Added BottomSheet to SettingsFragment
polarxdev/FinancialPortfolio pull request #9
Opened 2024-07-29 12:58 UTC by polarxdev

###**Changes**
Added usage of BottomSheet
Added saving settings using SharedPreferences

2024-07-29 13:21 UTC, tosqaaa commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetFragment.kt
> +    private lateinit var recyclerView: RecyclerView
Наверно не стоит recycler и adapter выносить в качестве полей класса. Наверно проще будет инициализировать эти переменные сразу в методе onCreateView

2024-07-29 13:22 UTC, tosqaaa commented on app/src/main/res/layout/fragment_bottomsheet.xml
> +        android:id="@+id/textView2"
Может стоит исправить нейминг?

2024-07-29 13:23 UTC, tosqaaa commented on app/src/main/res/layout/fragment_settings.xml
> +        android:text="Change"
через ресурс?

2024-07-29 13:25 UTC, tosqaaa reviewed
Нужно подправить.

2024-08-10 11:47 UTC, polarxdev commented
PR содержит много файлов не по теме BottomSheet'a т.к. пришлось фиксить много конфликтов и ошибок.

2024-08-12 13:12 UTC, Valentin2508247 requested changes

2024-08-12 13:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/SettingsFragment.kt
> +        lifecycleScope.launch {
лучше не мешать flow и livedata для подписок
сделай отдельную livedata во вьюмодели

2024-08-12 13:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetFragment.kt
> +            lifecycleScope.launch {
без launch

2024-08-12 13:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetFragment.kt
> +        list = arrayListOf("BYN", "CNY", "RUB", "EUR", "USD")
плохо так хардкодить

2024-08-12 13:12 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetListAdapter.kt
> +    private val context: Context,
нужен ли private val context: Context?

2024-08-12 13:12 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_settings.xml
> +        android:layout_height="wrap_content"
0dp?

2024-08-12 13:12 UTC, Valentin2508247 commented on app/src/main/res/layout/item_settings.xml
> +        android:text=""
удали android:text=""

2024-08-15 12:19 UTC, Valentin2508247 requested changes

2024-08-15 12:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/SettingsFragment.kt
> +            bottomSheetFragment.show(childFragmentManager, bottomSheetFragment.tag)
TAG у фрагмента по умолчанию отсутствует
ты по-сути задаешь пустой TAG
сделай const val TAG = "CurrencyBottomSheetFragment" в companion BottomSheetFragment
и передавай BottomSheetFragment.TAG

2024-08-15 12:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/SettingsViewModel.kt
> +            return@launch settingsInteractor.saveCurrencyToPreferences(currency, context)
убери return@launch

2024-08-15 12:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetFragment.kt
> +class BottomSheetFragment(private val settingsViewModel: SettingsViewModel) :
лучше, если у фрагментов пустой конструктор
переданные в конструктор аргументы не восстановятся при восстановлении фрагмента из кеша
используй общепринятые методы получения viewModel / sharedViewModel

2024-08-15 12:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetFragment.kt
> +    private val list = settingsViewModel.getSettingsList()
тут блокирующее получение данных при создании фрагмента, плохо так писать
лучше сделать так:
1. запросить данные у viewModel в onViewCreated
2. viewModel отправит данные в liveData
3. обработать данные в observe liveData

2024-08-15 12:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetListAdapter.kt
> +        val item = list[position]
вынеси логику в метод вьюхолдера
привязка данных к view - обязанность viewHolder

2024-08-15 12:19 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetListAdapter.kt
> +        val view = LayoutInflater.from(parent.context)
создай сразу ViewBinding и передавай во ViewHolder

2024-08-16 18:07 UTC, pzinkevich42innowise commented on app/build.gradle
> +    implementation "androidx.datastore:datastore-preferences:1.0.0"
1. старая версия https://developer.android.com/topic/libraries/architecture/datastore#preferences-datastore-dependencies
2. А файл с версиями тебе для чего? У тебя вон выше кучу раз подключались библиотеки. Ты когда вставлял это с какой-то левой статьи, тебя не смутило, что код не так написан и надо бы разобраться почему?

2024-08-16 18:09 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/data/SettingsRepositoryImpl.kt
> +    override fun readCurrencyFromPreferences(): Flow<String> {
А зачем тут в названии метода указывать реализацию?

2024-08-16 18:09 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/data/datasource/SettingsDataSource.kt
> +    fun readCurrencyFromPreferences(): Flow<String>
Зачем куда-то отдавать Flow в этой ситуации?

2024-08-16 18:14 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/data/datasource/local/LocalSettingsDataSource.kt
> +    private val CURRENCY: Preferences.Key<String>
Это в DI не надо складывать. DI для внешних зависимостей, а это внутренняя. Определяй её внутри этого класса

2024-08-16 18:15 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/data/datasource/local/LocalSettingsDataSource.kt
> +    private val settingsList = listOf("BYN", "CNY", "RUB", "EUR", "USD")
Это вообще константы на весь проект и в Domain лежать должны, и отовсюду их использовать

2024-08-16 18:16 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/settings/SettingsFragment.kt
> +            bottomSheetFragment.show(childFragmentManager, BottomSheetFragment.TAG)
навигацию используй тут

2024-08-16 18:17 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetFragment.kt
> +class BottomSheetFragment: BottomSheetDialogFragment() {
Может внятное название можно дать?

2024-08-16 18:18 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolio/presentation/settings/bottomsheet/BottomSheetFragment.kt
> +    private val settingsViewModel: SettingsViewModel by activityViewModels()
почему не обычный viewModels?

2024-08-16 18:19 UTC, pzinkevich42innowise commented on app/src/main/res/layout/item_settings.xml
> +    android:layout_height="wrap_content">
Какую роль выполняет тут лайнир?

2024-08-18 18:31 UTC, pzinkevich42innowise commented on app/src/main/res/layout/item_settings.xml
> +    android:layout_height="wrap_content">
Кажется эта обёртка лишняя

2024-08-18 18:32 UTC, pzinkevich42innowise approved these changes
Поправь вёрстку и вливай

2024-08-19 13:50 UTC, merged